# boil Configuration File

# Project Settings
project_name: my-awesome-project

# OpenAI Settings
openai_api_key: your-api-key-here
model_name: gpt-4o-mini

# Project Component Flags
git_repo: true
git_ignore: true
readme: true
dockerfile: false
